---
- name: Install packages
  package:
    name: "{{ packages }}"
    state: present

- name: Create SpaceVim.d directory
  file:
    path: "{{ ansible_env.HOME }}/.SpaceVim.d"
    state: directory

- name: Get init.toml file
  get_url:
    url: https://raw.githubusercontent.com/SpaceVim/SpaceVim/master/mode/dark_powered.toml
    dest: "{{ ansible_env.HOME }}/.SpaceVim.d/init.toml"

- name: Get SpaceVim install script
  get_url:
    url: https://spacevim.org/install.sh
    dest: /tmp/install.sh

- name: Install SpaceVim
  shell: bash /tmp/install.sh

- name: Add custom vim plugins
  blockinfile:
    path: "{{ ansible_env.HOME }}/.SpaceVim.d/init.toml"
    insertafter: EOF
    content: "{{ custom_vim_plugins }}"

- name: Add autoformat terraform on save to vimrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.SpaceVim/vimrc"
    insertafter: EOF
    line: 'let g:terraform_fmt_on_save=1'
